### ISSUE TITLE
Maven dependencies are sometimes downloaded in home folder

### ISSUE THREAD

**Issue by gbaso** [eclipse-m2e/m2e-core#383]
Despite having a valid `~/.m2/repository` folder, used by maven when invoked via CLI and by Eclipse when updating maven project, I periodically find my home folder littered by top level folders for dependencies (e.g. `com`, `org` and `jakarta`) with related dependencies inside, plus an empty `index` folder. If I delete them the application still works, but eventually they are recreated.

I am not sure which event triggers it, but it happens more frequently when interacting with `pom.xml` or when starting Eclipse.

Possibly related to #169.

Using Eclipse 4.21, m2e 1.18.3.20211018-0804 (latest snapshot at the time of writing), Linux Mint 20.2.
Also using m2e-apt with the `Delegate annotation processing to maven plugins` option.

**Comment by vrubezhny** [comment]
@gbaso Are you sure you have empty location node in your settings.xml (`<localRepository />`) when you're getting the dependencies downloaded to your home folder? 
In my case (linux) the local repository path in such case is resolved to `~/.m2/repository` directory.
If I set it to any non-null value - that value is used to create a local repository even if it's not correct (like `~` character is used instead of real `/home/username` value, etc. - if a path can be created it will be created )
The env. variables available in eclipse are resolved (for example, `${HOME}` for me is properly resolved to `/home/<myusername>` directory).
So, I suppose that in order to reproduce the issue the `localRepository` is to be set to `${HOME}` with no any additions or to any variable that resolves to user home directory path.

**Comment by gbaso** [comment]
>  In my case (linux) the local repository path in such case is resolved to ~/.m2/repository directory.

That was my expectation as well, but I tried it on a clean VM and I could still reproduce the issue, so I don't think it's a problem on my end. The snippet in my previous comment was what I used verbatim.

**Comment by rgrunber** [comment]
FWIW, I've seen similar behaviour on https://github.com/redhat-developer/vscode-java/issues/2114 , although in that case, content is written directly to the project folder. The user claimed to even set `java.configuration.maven.{user,global}Settings`  (which on our end calls `MavenPlugin.getMavenConfiguration().set{User,Global}SettingsFile(..)` and the problem still occured.

**Comment by mickaelistria** [comment]
Issue is in lemminx-maven, this is being worked on at https://github.com/eclipse/lemminx-maven/pull/236

**Comment by mickaelistria** [comment]
This should now be resolved if you're using latest m2e snapshots.
