### ISSUE TITLE
Let m2e-maven-runtime use standard maven tooling / build

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#423]
Currently m2e-maven-runtime uses tycho to build, but disables most of it (running in pure maven mode, disable plugins, ...) and generates eclipse-metadtafiles that should be handled by m2eclipse instead. Some of these are there for historic reasons, others might reveal missing features either in pde or m2e.

We should step-by step remove those workaround to show-case that m2e+PDE is a fully featured solution to develop OSGi-Bundles "the maven way" without requiring any hacks or quirks.

**Comment by laeubi** [comment]
First thing we should address here is the following comment in the pom.xml configuration:

```
<!-- PDE does not honor custom manifest location -->
<manifestLocation>META-INF</manifestLocation>
```

according to my recent investigations this is not true. Importing a plain maven project using basic configuration of felix-maven-bundle-plugin shows that m2e generates the following PDE configuration file:

> .settings/org.eclipse.pde.core.pref
```
BUNDLE_ROOT_PATH=target/classes
eclipse.preferences.version=1
```

this makes PDE recognize that project as a plugin, even though there is [a bug that fails to launch the manifest editor for it](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577637).

Using no custom configuration here would also make us confident that this feature actually works.

Remaining issues are
- [ ] the META-INF/MANIFEST.MF file is not marked as derived, we should check if this could be done by the maven plugin or m2e itself @mickaelistria any comments? Compiled Classfiles are marked as derived but not resources.
- [ ] felix-bundle-plugin seems not to be updated always: https://github.com/eclipse-m2e/m2e-core/discussions/422

**Comment by laeubi** [comment]
Second issue: Why do we use tycho `eclipse-plugin` packaging for those plugins? The literally seem to do nothing that requires tycho at all. @HannesWell can you give some insights?

**Comment by mickaelistria** [comment]
> the META-INF/MANIFEST.MF file is not marked as derived

IIRC, m2e is in charge of marking some files as derived. However, current implementation is only about the default target/ folder. So if the plan is to put the MANIFEST in another location leveraging BUNDLE_ROOT and this location is in target, there is no need for more hacks here; the BUNDLE_ROOT approach seems to be a good solution and improving it support seems to be a more generic improvement that will generate more value.

**Comment by laeubi** [comment]
> and this location is in target, there is no need for more hacks here;

So if a folder is derived all descendant resources should also considered derived?

**Comment by mickaelistria** [comment]
> if a folder is derived all descendant resources should also considered derived?

Yes. However it's up to the caller to ensure it does treat "derived" that way and honor subtrees (by cutting branches while it crawl a tree, or using `isDerived(CHECK_ANCESTORS)`), the derived flag is not automatically propagated to subtree.

**Comment by HannesWell** [comment]
The main motivation/goal to make the plug-ins in m2e-maven-runtime ordinary Eclipse-Plugins was to enable their participation in the workspace build so they can be used in Eclipse-App launches and provide the sources to the developers without the need to reload the target-platform to reflect every change.
A secondary goal was to remove the m2e-maven-runtime bundles from the Target-Platform to simplify their management (to update the version every time a m2e-maven-runtime bundles changes, but this could be addressed with version ranges).

To achieve the main goal those actually Maven-projects had to become Eclipse-Plugins so PDE can build them (but this requirement likely becomes obsolete with your proposal #419).
The build is a.t.m. split into two steps: The first only generates the meta-data (i.e. the `MANIFEST.MF` and the `.classpath` file) and fetches the embedded jars of the m2e-maven-runtime components. The second is an ordinary Maven/Tycho build for all plug-ins of m2e (including the maven-runtime). Making the maven-runtime bundles Eclipse-Plugins also had the advantage that they don't had to be specified in the TP.

In the Dev-IDE the Oomph setup runs the first build to generate the meta-data. I also tested to use m2e's workspace-build for that but it either was not triggered reliably (as you also encountered in https://github.com/eclipse-m2e/m2e-core/discussions/422) or it lead to an endless loop (probably a change triggered MANIFEST generation, which emitted a change again).
But would be definitely better if this first build would be performed automatically and reliably by m2e in the Dev-Eclipse.

But I think we should not use the Maven-dependencies for workspace builds (to save the generation of the .classpath file), because the generated .classpath file refers to jars embedded in the plug-in, while the M2E-Container in the .classpath, refers to the jars in the local .m2 repo. If we were using the M2E-Container in the classpath, the jars in my .m2 repo would be used for workspace build, while at runtime (be it launched from the dev-workspace or in an stand-alone installation), OSGi/Equinox loads the classes from the `jars` folder within that bundle. Even though they _should_ be fully equal, it would be a potential inconsistency.

I didn't knew about the `BUNDLE_ROOT_PATH` feature, thanks for sharing that. But does it substantially change something, besides the location of the MANIFEST.MF? It looks to me that it just shifts the specification of the location from the pom to the settings?

Converting M2E's Maven-runtime bundles back into Maven-Projects is likely an interesting use-case for #419. But we would have to add the runtime plug-ins to the TP again. And it would not save us the two builds (unless Tycho would be capable to resolve the Target-Platform for a mixed reactor of Maven and Plug-in Projects), because the build would have to be performed like before where the builds where installed into a specified build-local repo.

**Comment by laeubi** [comment]
> ordinary Eclipse-Plugins was to enable their participation in the workspace build so they can be used in Eclipse-App launches and provide the sources to the developers without the need to reload the target-platform to reflect every change.

I think if we can fix the issue with felix-bundle-plugin there is a good chance this would work (at least to my limited testing).

> A secondary goal was to remove the m2e-maven-runtime bundles from the Target-Platform

If the above is working, I think it would work to add them as pom-considered maven deps to the tycho build, that way they won't appear in the target but can still be used as maven projects in the workbench.
I don't think that worspace-resoloution is a requirement for this.





> But I think we should not use the Maven-dependencies for workspace builds (to save the generation of the .classpath file), because the generated .classpath file refers to jars embedded in the plug-in, while the M2E-Container in the .classpath, refers to the jars in the local .m2 repo. If we were using the M2E-Container in the classpath, the jars in my .m2 repo would be used for workspace build, while at runtime (be it launched from the dev-workspace or in an stand-alone installation), OSGi/Equinox loads the classes from the `jars` folder within that bundle. Even though they _should_ be fully equal, it would be a potential inconsistency.

I think this is a very very paranoid view. We really should trust our tools, if we cant trust maven/m2e to do the right things we should think about ways to make them more trustworthy (e.g. add more tests).

> I didn't knew about the `BUNDLE_ROOT_PATH` feature, thanks for sharing that.

I didn't know either until I recently tried to add a similar feature to PDE and noticed it was just working right away :-D
Thats why I opened this ticket, as m2e is also using alot of workarounds how should users of m2e know there are better ways?



> And it would not save us the two builds (unless Tycho would be capable to resolve the Target-Platform for a mixed reactor of Maven and Plug-in Projects),

If pom-considered dependecies not work for us, this could be a good use-case to add support for this in tycho. I already investigated a bit and made some plans to support such "pom-first" projects.

**Comment by HannesWell** [comment]
> I think this is a very very paranoid view. We really should trust our tools, if we cant trust maven/m2e to do the right things we should think about ways to make them more trustworthy (e.g. add more tests).
> 
Alright, then lets try it.

> > ordinary Eclipse-Plugins was to enable their participation in the workspace build so they can be used in Eclipse-App launches and provide the sources to the developers without the need to reload the target-platform to reflect every change.
> 
> I think if we can fix the issue with felix-bundle-plugin there is a good chance this would work (at least to my limited testing).

When thinking more about this, yes it should work.

Given that the incorporated Maven-plug-ins reliable participate in the workspace-build, they can be used to fetch the jars (to be used at runtime of a Eclipse-app launched from the dev-workspace) and to generate a proper manifest. With the `BUNDLE_ROOT_PATH` feature we could re-direct PDE to use the Manifest from the target-folder, so we don't have to adjust resource inclusion with Maven.
Furthermore we likely can remove the `pde.ManifestBuilder` and `pde.SchemaBuilder`, but have to keep the `org.eclipse.pde.PluginNature`. As you said in the other issue this should be sufficient to let it participate in the PDE-build and to make a project consumable by other Plug-in projects?

To create a corresponding workspace build classpath for JDT we could use the Maven-container, so we can remove the antrun for this. Since the dependencies are stripped to those that are included this should fit. But we have to check what happens to embedded dependencies whoose packages are not exported in the Manifest. They could still become visible to other Plug-ins through the M2E container. But I have to check it, it would also possible that it simply works.

From M2E side we only have to ensure that (as you already listed) the following plug-ins and their goals participate well in the workspace build an reliable run on each incremental build:

- `maven-bundle-plugin`, goal `manifest`
- `maven-clean-plugin`, goal `clean`
- `maven-dependency-plugin`, goal `copy-dependencies`

The others ones might already work, I have not tested it yet?

> > A secondary goal was to remove the m2e-maven-runtime bundles from the Target-Platform
> 
> If the above is working, I think it would work to add them as pom-considered maven deps to the tycho build, that way they won't appear in the target but can still be used as maven projects in the workbench. I don't think that worspace-resoloution is a requirement for this.
> 
> > And it would not save us the two builds (unless Tycho would be capable to resolve the Target-Platform for a mixed reactor of Maven and Plug-in Projects),
> 
> If pom-considered dependecies not work for us, this could be a good use-case to add support for this in tycho. I already investigated a bit and made some plans to support such "pom-first" projects.

I think for a first iteration two builds are sufficient because the situation does not become worse. We can simply do it like before. Perform a first full Maven-build and install the m2e-runtime-bundles in a temporary local repo. Which is used in the second build that builds the actual m2e plug-ins. 
Having one build would indeed be very nice to have. But since it only has to be configured once in the Jenkins-file/maven.yml, I think it is not too important for this.

But I don't know exactly how to add a Maven-project as pom-consider project (I never had this use case yet and usually only work with either pure Maven or pure Eclipse/tycho builds).
We simply add the m2e-maven-runtime projects as dependencies to the root pom.xml and set pomDependencies=consider for the `target-platform-configuration` plug-in? Or could/should we use `dependency-resolution` or does this only work for p2-repos?

> > I didn't knew about the `BUNDLE_ROOT_PATH` feature, thanks for sharing that.
> 
> I didn't know either until I recently tried to add a similar feature to PDE and noticed it was just working right away :-D Thats why I opened this ticket, as m2e is also using alot of workarounds how should users of m2e know there are better ways?
> 
That happens to me also once in a while, it's the hard way to learn about existing features 😅 
That's right I also noticed that especially for OSGi and already made some changes in M2E, for example leverage OSGi's Wiring API (which I'm personally a big fan of, it makes working with dependencies very simple) to collect the jars that participate when launching a Maven-build using embedded Maven. Before it used hard-coded constants and was IMHO very unelegant.

We could upgrade the Maven-Project-Configurator to set up the `BUNDLE_ROOT_PATH` and the `.project` file accordingly so that if m2e detects that a Maven-project is a bundle/has a valid MANIFEST.MF it can seamlessly participate in the PDE workspace build. The question is how to detect it? If a plug-in like the maven-bundle-plugin with goal `manifest` or `bundle` is active or can we check it after a build?

The only completely open point for me at the moment, is how we can get the git-derived build qualifier for the Maven-projects? I don't know if this is available for pure Maven-projects? Could we still use Tychos build-qualifier mojo (in an adapted way)? Or should we drop the qualifier entirely and make it really Maven style using no qualifier at releases and -SNAPSHOT versions? (I' don't know if this is a bad idea or not).

Regarding the implementation of this issue: I think I have a relativly good idea what to do and can offer to take care of it (with medium priority) unless @laeubi you prefer to complete this issue by yourself (I could of course review it then).

**Comment by laeubi** [comment]
> Regarding the implementation of this issue: I think I have a relativly good idea what to do and can offer to take care of it (with medium priority)

Just go ahead an let me know if you need any help. I think we won't solve this in one big bang but maybe with some intermediate steps and as mentioned above may need  to resolve some other issues first.

> But I don't know exactly how to add a Maven-project as pom-consider project (I never had this use case yet and usually only work with either pure Maven or pure Eclipse/tycho builds).
> We simply add the m2e-maven-runtime projects as dependencies to the root pom.xml and set pomDependencies=consider for the `target-platform-configuration` plug-in?

That's how it is supposed to work.

**Comment by laeubi** [comment]
I think this is fixed (and released) if we have more issues we can use more smaller scoped tickets.

**Comment by HannesWell** [comment]
> I think this is fixed (and released) if we have more issues we can use more smaller scoped tickets.

If this ticket is only about how the maven-runtime projects in m2e are set up, this is not yet fixed, since I have not yet completed https://github.com/eclipse-m2e/m2e-core/pull/466
