### ISSUE TITLE
POM editor: shortcuts broken

### ISSUE THREAD

**Issue by 2019-05-10** [eclipse-m2e/m2e-core#429]
Since 1.19 previously working shortcuts are broken, for me most notably "Toggle Block comment".
In the normal XML editor thos still work.

Judging from the now different colors of syntax coloring the XML parts seems to have changed, but it sgtill should recognize/copy the shortcust/other settings of the previously used XML editor.

Eclipse:
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

M2E:
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature

**Comment by fbaligand** [comment]
I reproduce the issue.
This is clearly a annoying problem for me!

**Comment by JRaue** [comment]
+1 This is a highly annoying regression, hopefully easy to fix?

**Comment by lbeuster** [comment]
As a workaround uninstall the default pom editor (LemMinX) and install the legacy one (something like "POM Editor (Legacy) using WebTools..."). With the old editor some basic feature work again for me, e.g. "Open Declaration".

**Comment by mickaelistria** [comment]
I have fixed TM4E so the Ctrl+Shift+C shortcut is now working again for files like pom.xml. Please install latest version from https://download.eclipse.org/tm4e/snapshots/ and try again.

**Comment by Ravi201606** [comment]
The comments are still not working with shortcut ctrl+shift+/ shortcut in pom editor.

**Comment by scmod** [comment]
still not working
eclipse.buildId=4.24.0.I20220607-0700
TextMate Core	0.5.1.202209071331	org.eclipse.tm4e.feature.feature.group	Eclipse TM4E
and the single line comment is not right also, it end with a new line and '--'
