### ISSUE TITLE
Ctrl / Cmd + Click on parent does not open the pom

### ISSUE THREAD

**Issue by a1dutch** [eclipse-m2e/m2e-core#494]
When using a standard spring boot maven project you are not able to Ctrl / Cmd + Click on the parent for it to open the pom.

**Steps To Reproduce**

1) download the project from [here](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.6.2&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=devtools,lombok,web)
2) import into eclipse as a maven project
3) open the pom.xml and try to Ctrl / Cmd + Click on the parent
4) parent pom does not open, parent information/description can be seen on hover though

**Expected Behaviour**

The pom.xml of the parent should open in a new window.

Cheers

@a1dutch

**Comment by mickaelistria** [comment]
This should be fixed in snapshots when https://ci.eclipse.org/m2e/job/m2e/job/master/152/ is complete (in ~15 minutes)

**Comment by a1dutch** [comment]
@mickaelistria thanks, that works for immediate parents, but once the pom for the parent is open. you can not open that parent's pom.  it used to work in the old editor for as many parents.

e.g.
org.springframework.boot:spring-boot-dependencies:2.6.2 <- cannot view this pom
-org.springframework.boot:spring-boot-starter-parent:2.6.2 <- can view this
--com.example:demo:0.0.1-SNAPSHOT

**Comment by mickaelistria** [comment]
This should be fixed if you upgrade to latest m2e and lsp4e snapshots.
The patches that are supposed to fix it are both https://github.com/eclipse/lemminx-maven/commit/7cd6b7d0076a09690c443f44ace3f264fc8601e6 and https://github.com/eclipse/lsp4e/commit/1aa515cf7f83fc42f5dfae8314a2c494c0fb549c

**Comment by a1dutch** [comment]
i doesnt seem to work for me, once the spring-boot-starter-parent pom is open, im not able to Cmd + Click on the spring-boot-dependencies pom. see recording

https://user-images.githubusercontent.com/1457117/149574806-df49f930-7ca8-4226-85b6-ee1890911982.mov

These are the versions i was using

Language Server Protocol client for Eclipse IDE (Incubation)	0.13.9.202111251951
M2E Maven Integration for Eclipse Core	1.18.4.20220102-2116
M2E Maven POM File Editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components)	1.18.4.20220114-1100

**Comment by a1dutch** [comment]
Also in the opened pom it does not resolve any variables/properties and you cannot click on any dependencies and open their pom's either. i can open seperate issues for these if you like?

**Comment by mickaelistria** [comment]
> Language Server Protocol client for Eclipse IDE (Incubation) 0.13.9.202111251951

Newer version 0.13.9.202201141022 with a necessary patch is available at https://download.eclipse.org/lsp4e/snapshots/

**Comment by mickaelistria** [comment]
>  i can open seperate issues for these if you like?

No need to, it's the same issue/fix in LSP4E.

**Comment by a1dutch** [comment]
@mickaelistria brilliant that works alot better and i can open the poms all the way to the root (org.springframework.boot:spring-boot-dependencies:2.6.2), but i cannot Ctl + Click on any dependencies under dependency management
