### ISSUE TITLE
Java version mismatch between JRE_CONTAINER and targetPlatform in M2E 2.0.0

### ISSUE THREAD

**Issue by CsCherrYY** [eclipse-m2e/m2e-core#842]
steps to reproduce:

1. given sample project: https://github.com/mybatis/mybatis-3.git
2. open it in VS Code, with redhat.java extension 1.8.0 installed (which integrates m2e 2.0.0 snapshot).
3. after project imported, VS Code reports an error in `Item` record under package `org.apache.ibatis.submitted.record_type`.
> java.lang.Record cannot be resolved to a type.

as we know, record should be available in Java 16 but not in Java 8.

4. check the generated `.classpath` file, the JRE_CONTAINER is set to JavaSE-1.8 VM.
> classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"
5. check the generated `.settings/org.eclipse.jdt.prefs` file, the target platform is set to Java 16 (which would be the expect source level since it's defined in https://github.com/mybatis/mybatis-3/blob/9da3467e96a03e8bd6e040139581a22ce5297c29/pom.xml#L449-L459)
> org.eclipse.jdt.core.compiler.codegen.targetPlatform=16
org.eclipse.jdt.core.compiler.compliance=16
org.eclipse.jdt.core.compiler.source=16

if we rollback to redhat.java 1.6.0, which uses m2e 1.18.2, this issue disappears. The JRE_CONTAINER in .classpath file is JavaSE-16, and the value of pref `org.eclipse.jdt.core.compiler.codegen.targetPlatform` is also 16.

I think this issue might related to https://github.com/eclipse-m2e/m2e-core/pull/597 which introduces a new limitation from maven-enforcer-plugin. But I'm not sure it's caused by the plugin or m2e itself. When debugging, the two environments seem to mismatch:
![image](https://user-images.githubusercontent.com/45906942/177503837-46dd0f0e-b2dd-41bc-b1b6-fe862ecc2241.png)

cc: @fbricon @rgrunber

**Comment by mickaelistria** [comment]
Can you please provide steps to reproduce with plain Eclipse m2e? Or even better, as a unit test for org.eclipse.m2e.jdt.tests ?

**Comment by rgrunber** [comment]
I am able to reproduce with :

Version: 2022-06 (4.25)
Build id: I20220704-0600
M2E - Maven Integration for Eclipse	2.0.0.20220705-1608	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

This does not occur with the 1.x m2e :

M2E - Maven Integration for Eclipse (includes Incubating components)	1.20.1.20220227-1319	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

I just had to add a Java 1.8 JDK to "Installed JREs" so that it may be detected (if needed).

The pom file does have a profile :

```
    <profile>
      <id>16</id>
      <activation>
        <jdk>[16,)</jdk>
      </activation>
      <properties>
        <maven.compiler.testTarget>16</maven.compiler.testTarget>
        <maven.compiler.testSource>16</maven.compiler.testSource>
        <excludedGroups>TestcontainersTests,RequireIllegalAccess</excludedGroups>
      </properties>
    </profile>
```

Is this just a regression in detecting the Java runtime from the profile ?

**Comment by mickaelistria** [comment]
@rgrunber do you think you could turn this example into a test case for org.eclipse.m2e.jdt.tests?
@kwin any idea which part of the code too look at, that could be causing this inconsistency?

**Comment by mickaelistria** [comment]
> getExecutionEnvironmentId() is driven from maven-compiler-plugin settings 

And why does this return 16 here?

**Comment by kwin** [comment]
All mojo executions are considered at https://github.com/eclipse-m2e/m2e-core/blob/8b876a6748d8858578ee5894c40a872affc0e052/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/AbstractJavaProjectConfigurator.java#L612 and the last one actually wins (i.e. determines the compiler options).

**Comment by mickaelistria** [comment]
> All mojo executions are considered at 

OK, so that's probably the root cause of the bug. The test executions should be skipped.

**Comment by kwin** [comment]
Not sure, if maven-enforcer enforces a lower version, but you have a profile (conditionally activated) setting the target of the compiler (not only for test) you also run into this issue. So in general the JRE container should be the highest one from the different parameterisations.

**Comment by CsCherrYY** [comment]
> Here the test compilation should be ignored, or only the default compilation considered. Other compilations are supplemental and manage things on a grain the doesn't map well in Eclipse m2e anyway.

@mickaelistria In this way, IIUC both the project's compliance and the JRE container of that sample project would be set to 1.8 since only the default compilation considered, right? And can we do something with the tests in source level 16?

**Comment by mickaelistria** [comment]
> IIUC both the project's compliance and the JRE container of that sample project would be set to 1.8 

Yes.

> And can we do something with the tests in source level 16?

No. JDT cannot be configured to compile the sources from a given project with different compiler options (eg source level). Changing that would require a fair amount of work in JDT, to move the various options from project-scope only to source-folder scope. Then, when JDT can do it, m2e can leverage it.

**Comment by CsCherrYY** [comment]
Yeah, and I'm thinking since JDT use the same compiler option for a project, why not use the highest version between them, as @kwin 's new proposal? 

I can imagine that if we set the source compiler level of the project to 1.8, users will encounter errors about `record` in tests. While if we use the higher of them (16), it can solve this issue and no further compiler error will appear (since language level 16 is compatible with level 8)

**Comment by laeubi** [comment]
> No. JDT cannot be configured to compile the sources from a given project with different compiler options (eg source level). Changing that would require a fair amount of work in JDT, to move the various options from project-scope only to source-folder scope. Then, when JDT can do it, m2e can leverage it.

I don't think that it needs to be that complex, JDT already distinguish between "main" and "test" sources and even classpath entries and seem to compile them differently, so it seems possible to even use a different compiler level then for test sources.

**Comment by kwin** [comment]
>  so it seems possible to even use a different compiler level then for test sources.

At least via UI that option is not exposed in Eclipse and having some options for compilation which are not exposed in UI calls for trouble as there is too much magic in it then.

**Comment by laeubi** [comment]
> At least via UI that option is not exposed in Eclipse

I don't think it is currently possible, just not that we need a setting per source folder as indicated by @mickaelistria 

> having some options for compilation which are not exposed in UI calls for trouble as there is too much magic in it then.

Compiling code with higher JVM level could also be a source of problems as it might "leak" into your Java 1.8 code.

**Comment by CsCherrYY** [comment]
> JDT already distinguish between "main" and "test" sources and even classpath entries and seem to compile them differently 

AFAIK JDT indeed distinguish these two sources but can't use different options to compile them, and only compiler prefs such as "org.eclipse.jdt.core.compiler.compliance" can be found. @laeubi could you please explain a little bit? 

@mickaelistria what do you think of this?

**Comment by laeubi** [comment]
JDT needs to be enhanced to have e.g. `org.eclipse.jdt.core.compiler.test.compliance` ...

**Comment by MrThaler** [comment]
> Moreover a pom setup that mixes different version in enforcer and main compilation would be inconsistent even from Maven POV, so no need to worry further about it in m2e.

The purpose of the enforcer rule is to set a **range** of acceptable versions, e.g. "Java 8 and above" or "Any Java version between 7 and 11". If that condition is not met, the enforcer rule does not adjust compilation target - it simply aborts the build process.
So it is a perfectly valid setup to **enforce** a Java version of Java 8 and above, but **actually compile** with and for Java 11. I would argue this is even the *purpose* of that particular enforcer rule.

As it is right now, the Build Process would state "I'm compiling with Java 11 for Java 11. I'm also verifying that both of these versions are newer than Java 8" and m2e would go "Clearly we should use Java 8 to run this then" - in essence turning a rule that says "At least one version in range must be able to compile and run the code" into "The lowest version in range must be able to compile and run the code" which is not a bug in the `pom.xml`, but m2e.

**Comment by hazendaz** [comment]
I'm the maintainer of the mybatis projects.  The parent pom is set to detect m2e.version property.  Does that even exist still?  This worked prior to 2.x m2e jump.

Via this profile (from https://github.com/mybatis/parent/blob/master/pom.xml)

```
    <profile>
      <id>eclipse</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
```

```
            <!-- Force Eclipse to use test side in order to ensure no compilation errors (generally these are same and make no difference) -->
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                <source>${maven.compiler.testSource}</source>
                <target>${maven.compiler.testTarget}</target>
              </configuration>
            </plugin>
```

So the issue here should be setting the entire thing to jdk 16 as required for mybatis-3 to compile tests at least and known that it all must go there even though bulk is jdk 8 based code.  We have also moved off using jdk 8 at all for builds now.  So currently, a fresh import of mybatis-3 shows up with JavaSE-12 being selected.  I'm unclear where 12 is even coming from.  The required java version in parent on enforcer plugin is an allowable range 11, 17, 18, 19, 20 in our latest.

**Comment by laeubi** [comment]
As far as I know nothing has changed here. The JVM itself are configured under `Window > Preferences > Java > Installed JREs` there you can see what JRE maps what java version.

What m2e actually has derived, should be stored in `<your project>/.settings/org.eclipse.jdt.core.prefs` > `org.eclipse.jdt.core.compiler.compliance=<derived java version>`

**Comment by laeubi** [comment]
> This is just not possible, as the compiler uses the same JDK as the rest of the build by default. And Java 8 cannot compile for Java 11.

Tycho can compile with any java version, also plain maven can do this, using configured toolchains.

**Comment by hazendaz** [comment]
ok the file itself shows 16.  odd though its not selecting that in the ide.

**Comment by MrThaler** [comment]
> > So it is a perfectly valid setup to enforce a Java version of Java 8 and above, but actually compile with and for Java 11.
> 
> This is just not possible, as the compiler uses the same JDK as the rest of the build by default. And Java 8 cannot compile for Java 11.

You are misunderstanding me. I'm not saying to use Java 8 to compile for Java 11. I say it is possible that you enforce a *minimum* of Java 8, but are *actually* using Java 11.
If I have a sign stating "You must be this tall to enter" I'm not chopping of a few inches for you to get down to size, it's a **minimum**. If I have an enforcer rule stating "All public methods must have a Javadoc" I am still free to write Javadoc for my private methods. It's a valid setup for a company to utilize an enforcer rule to force all of their developers to use a minimum of Java 8, but allows for them to use Java 11 in their projects if they so desire.

Again, it is not the job of the enforcer rule to **set** the used Java version. It's the job of the enforcer rule to **validate** that the used Java version follows the given guidelines. So m2e ignoring the actually used version in the build and instead utilizing the enforced minimum version is simply wrong behavior, ignoring something explicitly set for a minimum it basically guesses.

**Comment by laeubi** [comment]
I'm not sure if this applies here, for sure if I set the minimum to java 8, would expect that it works on java 8 and above, so I need to actually compile for Java 8 and don't use any Java 11 features even if >= 8 is satisfied by java 11...

**Comment by MrThaler** [comment]
That is an expectation that is not completely unreasonable and I get where you're coming from. But if that was intended by Maven, why use ranges in the first place?

Large organizations might (and often will) have some broader rules defined in the company-wide parent pom. A change in m2e should not break a project that has both valid parent pom, was previously buildable with m2e and is buildable without issues through Maven itself.

**Comment by kwin** [comment]
> why use ranges in the first place?

Pretty common to require new JDKs than the Java version you are targeting (e.g. Maven plugins requiring Java 8, while your code targets 7, then m-enforcer-p would require JDK8 or newer)

**Comment by hazendaz** [comment]
Isn't the solution here easy?  the m2e config files all state 16.  So it would only make sense that the classpath match that.  In the latest release of mybatis, this no longer selects 8, its selecting 12 at least for me.  Unclear how it jumped there when enforcer now requires 11 at a minimum.

**Comment by famod** [comment]
I'm seeing the same as described initially but in my case (an oomph setup file for my current project that's working fine with Eclipse 2022-06) all projects are red/broken after import because I don't have Java 18 installed.

`.settings/org.eclipse.jdt.prefs` says 17, which is correct but `.classpath` says:
```xml
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-18">
                <attributes>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
```
I do have
```xml
        <java.version.full>17.0.4</java.version.full>
        <java.version.full.enforcer>${java.version.full}</java.version.full.enforcer>   <!-- if reported version differs a bit, e.g. 17.0.3.1 vs. 17.0.3-1 -->
...
                                <requireJavaVersion>
                                    <version>${java.version.full.enforcer}</version>
                                </requireJavaVersion>
```

I find this rather severe?

**Comment by famod** [comment]
I just realized that this issue is more about Java 1.8, but in my case it selects non-existent Java 18 instead. Still, the root cause might be the same.

**Comment by famod** [comment]
It's definitely `requireJavaVersion`: as soon as I remove it and do Maven -> Update Project... then all is well.

Furthermore:
Works:
```
<requireJavaVersion>
    <version>17</version>
</requireJavaVersion>`
```
Fails:
```
<requireJavaVersion>
    <version>17.0.4</version>
</requireJavaVersion>`
```

So the evaluation of what's set for enforcer pluginin is buggy.

**Comment by kwin** [comment]
The version being given in rule requireJavaVersion is always a range: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html.
That means that `<version>17.0.4</version>` is equivalent to `<version>[17.0.4,)</version>, i.e. everything greater or equal than 17.0.4 works. However Eclipse only knows major environment version ids, therefore it sets the minimum version to 18 in that case.

The exact source code is in https://github.com/eclipse-m2e/m2e-core/blob/8b876a6748d8858578ee5894c40a872affc0e052/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/AbstractJavaProjectConfigurator.java#L878-L897.

Feel free to suggest how to better support this edge case.

**Comment by famod** [comment]
@kwin thanks for your reply.

Setting `[17.0.4]` does avoid this problem, so thanks for poining that out (in fact, I think we had this range set at some point but it might got lost during a refactoring).

> However Eclipse only knows major environment version ids, therefore it sets the minimum version to 18 in that case.

Leaving that version range aspect aside for a moment, my major gripe is that m2e shouldn't fall back to a JVM that's not even installed.

**Comment by kwin** [comment]
> Leaving that version range aspect aside for a moment, my major gripe is that m2e shouldn't fall back to a JVM that's not even installed.

What should happen if Eclipse doesn't find a compatible JRE for the identified minimum execution environment from your PoV?

**Comment by kwin** [comment]
Maybe we need to check for https://help.eclipse.org/latest/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/launching/environments/IExecutionEnvironment.html#getDefaultVM() in https://github.com/eclipse-m2e/m2e-core/blob/8b876a6748d8858578ee5894c40a872affc0e052/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/AbstractJavaProjectConfigurator.java#L259 and fall back to the workspace default if no compatible VM is found.

**Comment by kwin** [comment]
@famod Please try out https://github.com/eclipse-m2e/m2e-core/pull/981

**Comment by HannesWell** [comment]
Is this issue completely fixed with #981?

**Comment by kwin** [comment]
The error reports are all a bit fuzzy here, so the only thing which has actually changed with #981 is that only Java levels which have a compliant installed JRE are selected and that minor versions are disregarded (because Eclipse only distinguishes [OSGi execution environments](https://docs.osgi.org/reference/eenames.html), i.e. major Java versions)

**Comment by hazendaz** [comment]
@HannesWell Issue is not resolved.  With latest m2e 2.1.3, its now importing fresh project noted here as JRE-1.1 and then setting that to jdk 17.  JRE-1.1 is not setup for any execution environment and java version was set to 11.  It really should not be using enforcer plugin to guess its way to glory.  The compiler args already told it what version.  This is a large problem when super poms support wide ranges.

**Comment by hazendaz** [comment]
note: 17 picked above as its the default in my Eclipse.  Other concerns still stand, it picks wrong execution environment.

**Comment by kwin** [comment]
A lot of different issues have been reported in this ticket. If still a JRE is picked which is not the enforced Java version or the target version then I would suggest to create a new ticket, with detailed information/example pom and expected JRE version and actual JRE version.

**Comment by HannesWell** [comment]
> @HannesWell Issue is not resolved. With latest m2e 2.1.3, its now importing fresh project noted here as JRE-1.1 and then setting that to jdk 17. JRE-1.1 is not setup for any execution environment and java version was set to 11. It really should not be using enforcer plugin to guess its way to glory. The compiler args already told it what version. This is a large problem when super poms support wide ranges.

OK. Could it be that you have the same issue like in https://github.com/eclipse-m2e/m2e-core/issues/1099? I'm about to look into that.

In general, from my understanding (also influenced by this discussion) of how to use the enforcer-plugin and the `source`/`target`/`release` properties of the `maven-compiler-plugin` I think M2E should do the following:
- Configure the JDT `...compiler.source`/`...compiler.codegen.targetPlatform`/`...compiler.release` preferences according to the corresponding configuration of the maven-compiler-plugin.
- In general set the `JRE_CONTAINER` in the project's `.classpath` to the value of the `source`/`target`/`release` properties of the `maven-compiler-plugin
  - in case of different versions, `release` wins, and if only `source` and `target` are specified the higher of both is used?
  - If a enforcer-plugin execution with `requireJavaVersion` rule is configured and that rule requires a **higher** Java version than specified by the compiler-plugin, then the lowest possible java (major) version that satisfies the rule's version range should be set as `JRE_CONTAINER`.
Personally I never really used the enforcer plugin yet, but from my understanding it is used to enforce the usage of a JDK with a higher version than the targeted Java version when building the sources. Since one cannot target more recent java versions than the JDK used to build is of, the compiler-plugin settings are the minimum. And reasonably the enforcer-plugin can only require the usage of more recent JDKs (for whatever reason). Therefore I think the suggested approach would best mimic the behavior of the build.

Does anybody disagree with that analysis?
If this is the desired behavior the second step is to make sure M2E acts accordingly.

@Bananeweizen maybe you are interested in this discussion as well.

**Comment by hazendaz** [comment]
It's simple.  Enforcer just states a level that must be used to even build.  So say jdk 11.  It typically has a range that are known to work.  However m2e only cares about what must be used to work.  Without Enforcer it should use source or release.  Target doesn't matter as one cannot compile upwards.  This broke with m2e 2.x.  it's now not selecting correct execution environment at 2.1.3.  It is working now at least in my case as default jdk was 17 but I have 8, 11, 17, 19, and 20 defined as execution environments and expected 11 not 1 from execution list.  I kind of question why eclipse has such old entries but don't feel m2e should even consider those.

A diagram probably would help map this out properly.  Also, probably rechecking why 2.x broke in this way.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Didn't tycho move to java 17?  Their latest tools from what I recall did so other issue seems valid as to 17 in general.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by laeubi** [comment]
> Does anybody disagree with that analysis?

I think there are actually two levels:

1. Compile time (and that's what `JRE_CONTAINER` maps to and I don't see a reason why enforcer should have any influences here...)
2. Runtime (e.g. running the tests from within eclipse, running a main-class, ...) where enforcer becomes relevant.

**Comment by hazendaz** [comment]
If enforcer says to use 11 while compile says 8. There is a bigger reason.  Plugins likely require 11 to function so rather than build failing with class version issue, it fails with nicer error to use 11 or better usually in a range.  The mybatis setup is correct.  I wrote it.  Same setup is in many other projects.  It has extra enforcer rules along with release that enforces binary compatibility.  Use that as a guideline since it was brought up originally by others.  That same setup I have on 1k repos or more at my day job via super pom.  Try the build at command line.  Use jdk8.  It will fail telling you to use 11 or better.  Use 11 it works, try 17, 19, 20ea,  all work.  See github actions, all executed, all valid.  So m2e should react the same there.  It has the range.  It should know to attempt the right minimum match.  If it cannot match it should not import and should tell user why.  Enforcer is just a hint on ranges that compiler must use. The compiler with source or release arg must also be at least the level of enforcer rule allows.  So let's say compiler say 17 in such case and enforcer says 11, 17, or 19.  Then clearly it must be 17.  If no enforcer the again must be 17 in this example.

Further note that tests can actually split from normal compiler args.  So tests could also further say even higher version still and that has to win out.  So back to my example if tests say they need 19, enforcer said ok range included 19, and compiler says 17, then 19 must be used.

Will open a new ticket. Include all related flags in clear way and link back here later today.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Opened #1120 that should help this entirely and has sample projects which the most broken up configuration between src/test and legacy vs modern setup and small project samples on live projects that have been configured as such for a long time and should be ideal in helping understand all this.
